# Generated by Django 4.2.4 on 2023-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_signup_password_remove_signup_repeat_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
